- name: "To filter and append the data to tempfile"
  lineinfile:
    path: "{{ item }}_temp.csv"
    create: yes
    line: "{{ item.stdout_lines | select('match', regex) | map('regex_replace', pattern, replace) | join(',') }}"
  vars:
    regex: '^(ADSMNODE|MAX_VERSIONS|MAX_SESSIONS|BRBACKUPMGTCLASS|BRARCHIVEMGTCLASS).*'
    pattern: '^\s*\w+\s+'
    replace: ''
  loop: "{{ util }}"




- name: Filter data from stdout_lines using select filter
  debug:
    msg: "{{ output.stdout_lines | select('search', 'filter_criteria') | list }}"


- name: Filter data from stdout_lines using regex_search filter
  debug:
    msg: "{{ output.stdout_lines | regex_search('regex_pattern') }}"


---
- name: "Playing with Ansible and Git"
  hosts: localhost
  tasks:
    - name: Fetch specific words
      command: grep -E 'ADSMNODE|MAX_VERSIONS|MAX_SESSIONS|BRBACKUPMGTCLASS|BRARCHIVEMGTCLASS' test.utl 
      register: words_output
        
    - debug:
        msg: "{{ words_output }}"    

    - debug:
        msg: "{{ words_output.stdout_lines | select('search', 'BRBACKUPMGTCLASS') }}"



---
- name: "Playing with Ansible and Git"
  hosts: localhost
  tasks:
    - name: Fetch specific words
      command: grep -E 'ADSMNODE|MAX_VERSIONS|MAX_SESSIONS|BRBACKUPMGTCLASS|BRARCHIVEMGTCLASS' test.utl
      register: words_output

    - debug:
        msg: "{{ words_output }}"

    - debug:
        msg: "{{ words_output.stdout_lines | select('search', 'BRBACKUPMGTCLASS|ADSMNODE|MAX_VERSIONS|MAX_SESSIONS')| match('^'BRBACKUPMGTCLASS|ADSMNODE|MAX_VERSIONS|MAX_SESSIONS'.*$') | map('replace', '#', '') | list }}"