---
  - name: "To get the Database Backup Process"
    find:
      paths: /home/ubuntu
      patterns: "*.utl"
      recurse: no
    register: utlfiles

  - set_fact: 
      util: "{{ utlfiles.files | map(attribute='path') | list }}"

  - debug: 
      var: util