---    
    - name: " Remove Temp file beining of Play"
      file:
        path: /oracle/all.csv
        state: absent    

    - name: Get the last word of processes named ora_pmon
      shell: ps -ef | grep ora_pmon | awk '{ print $8 }' | grep -v grep | awk -F "_" '{print $NF}' | grep -v /bin/sh
      register: last_word

    - set_fact: 
        dbname: "{{last_word.stdout_lines}}"

    - name: Print the DB Names
      debug:
        var: last_word.stdout_lines

    - name: "To get the all util file on server"
      find:
        paths: /oracle/{{ item }}/tsm/
        patterns: "*.utl"
        recurse: no
      register: utlfiles
      loop: "{{ dbname }}"       
      
    - set_fact:
        util: "{{ util|default([]) + item.files|map(attribute='path')|list }}"
      loop: "{{ utlfiles.results }}"

    - debug:
        msg: "{{ item.files | map(attribute='path') | list }}"
      loop: "{{ utlfiles.results }}"

    - debug: 
        var: util

    - name: "To filter and append the data to tempfile"
      shell: cat {{ item }} | grep -E 'ADSMNODE|MAX_VERSIONS|MAX_SESSIONS|BRBACKUPMGTCLASS|BRARCHIVEMGTCLASS' | awk '{ print $1,$2 }' | grep -v '#' | awk '{ print $2 }'  >> {{ item }}_temp.csv
      register: output  
      loop: "{{ util }}"      

    - name: "To append the filtered data to final file with DB names"
      shell: awk -F ',' '{ for (i=1; i<=NF; i++) { a[i,NR]=$i } } END { for (i=1; i<=NF; i++) { for (j=1; j<=NR; j++) { printf "%s%s", a[i,j], (j==NR ? "\n" :",") } } }' {{ item }}_temp.csv >> /oracle/all.csv
      register: output 
      loop: "{{ util }}" 

    - name: " To remove the temp files"
      shell: rm -rf {{ item }}_temp.csv
      loop: "{{ util }}" 