---
   - name: To cancel the Process for Database Backup
     shell: cat {{ item }} | grep -E 'ADSMNODE|MAX_VERSIONS|MAX_SESSIONS|BRBACKUPMGTCLASS|BRARCHIVEMGTCLASS' | awk '{ print $1,$2 }' | grep -v '#' | awk '{ print $2 }'  >> {{ item }}_temp.csv
     register: output  
     loop: "{{ util }}"  